name: Mega Package Build Workflow

on:
  workflow_dispatch:
  push: 
    branches:
      - feature
    paths-ignore:
      - '**/README.md'
      
jobs:
  call-reusable-workflow:
    uses: megafortunagames/mega.builder/.github/workflows/mega_package_builder.yml@main
